version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    command: ["/start-reload.sh"]
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - ./app:/home/app
    depends_on:
      - postgres

  # Postgres Databases
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

volumes:
  postgres_data: